disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - large_tuple
  - function_parameter_count
  - private_over_fileprivate
  - comment_spacing
  - multiple_closures_with_trailing_closure
  - todo

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count

included: # paths to include during linting. `--path` is ignored if present.
  - Rio
  - RioTests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Packages
  - build
  - Assets.xcassets
  - "*.generated.swift"

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning
force_try:
  severity: warning

# More lenient identifier naming for existing codebase
identifier_name:
  min_length: 1 # allow single character variables like 'L', 'dt', etc.
  excluded: # excluded via string array
    - id
    - url
    - URL
    - dt
    - dx
    - dy
    - p0
    - p1
    - p2
    - now
    - x
    - y
    - L
    - A
    - B
    - GlobalAPIKey

type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 80

reporter: "xcode"

custom_rules:
  no_empty_line_after_brace:
    included:
      - ".*\\.swift"
    name: "No Empty Line After Brace"
    regex: "\\{[ \\t]*\\n[ \\t]*\\n"
    message: "Remove empty line directly after opening brace."
    severity: warning
  no_empty_line_between_closing_braces:
    included:
      - ".*\\.swift"
    name: "No Empty Line Between Closing Braces"
    regex: "\\}[ \\t]*\\n[ \\t]*\\n[ \\t]*\\}"
    message: "Remove empty line between closing braces."
    severity: warning
  blank_line_after_closing_scope:
    included:
      - ".*\\.swift"
    name: "Blank Line After Closing Scope"
    regex: "(?:^|\\r?\\n)[ \\t]*[\\}\\)][ \\t]*\\r?\\n[ \\t]*(?!(?:[#./]|\\}|\\)|case\\b|default\\b|catch\\b))\\S"
    message: "Insert a blank line after closing brace or parenthesis."
    severity: warning
  blank_line_before_control_flow:
    included:
      - ".*\\.swift"
    name: "Blank Line Before Control Flow"
    regex: "(?m)^(?!(?:@|//|#|/\\*|\\{[ \\t]*$))([^\\s].*)\\n(?:if|guard|do|switch|for|while|func)\\b"
    message: "Add a blank line before control flow or function declarations."
    severity: warning
